[package]
name = "subpub"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "A publish and subscribe framework"
repository = "https://github.com/voxelphile/subpub"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]